name: TheFramework
version: '1.0.1'
main: me.mcplugins.theframework.TheFramework
load: STARTUP
api-version: '1.21'
author: Orange
description: The only plugin you need

commands:
    rel:
        description: "Reload the plugins"
        usage: "/rel"
        aliases: [ rel ]
        permission: framework.reload

permissions:
    framework.reload:
        default: op